version: "3.4"
services:
  profile:
    build:
      context: .
      target: dev
      args:
        TARGET_DIR: /app
        GOBIN: /app
        SSH_PRIVATE_KEY: |-
          ${SSH_PRIVATE_KEY}
    ports:
      - "8030:8030"
    env_file:
      - .env
    volumes:
      - .:/go/src/github.com/levongh/profile
    depends_on:
      - db
    networks:
      - default
      - web_app

  db:
    image: postgres:13
    command: [ "postgres", "-c", "log_statement=all" ]
    restart: always
    ports:
      - 5440:5432
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_DB: "postgres"
      POSTGRES_PASSWORD: "postgres"
    volumes:
      - pgdata:/var/lib/postgresql/data

  jaeger:
    image: jaegertracing/all-in-one:1.24
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "9411:9411"

  mailcatcher:
    image: schickling/mailcatcher
    ports:
      - 1080:1080
      - 1025:1025

networks:
  web_app:
    external: true
